### ISSUE TITLE
Add a project listing page

### ISSUE THREAD

**Issue by sumnerevans** [ColoradoSchoolOfMines/mozzarella#13]
Maybe this can become part of Show and Tell.

### TODO

- [x] Add Project database model
- [x] Display project information on the Projects page
- [ ] ~Display user's projects on their profile page?~ (deferred to #36)

**Comment by jackrosenthal** [comment]
If it needs database associations with things like Show & Tell project, then this might be a worthwhile feature. Otherwise, I think we could just list projects on the Wiki I proposed.

**Comment by sumnerevans** [comment]
My idea was that we would create this project listing page as a base to start integrating Show & Tell from.

**Comment by jackrosenthal** [comment]
Yes, in that case good idea.

**Comment by sumnerevans** [comment]
@bjessing suggested a design for this in #15.

**Comment by sumnerevans** [comment]
When Sam, Daichi and I made Show and Tell, we had a concept of Teams. I'm not sure that that is necessary though, I honestly think we can just have a list of people associated with each project.

Thoughts @jackrosenthal, @samsartor?

**Comment by jackrosenthal** [comment]
Fundamentally, isn't a team just a M:N xref between users and projects anyway?
The way I see it is that there are equivalent ways to write this, one of them
just names that xref a "team".

**Comment by sumnerevans** [comment]
Good point. One twist is that Team is M:N for users, but not projects (you can only have one team working on a project). The way we modeled it in Show and Tell was `Person--M:N--Team--A:1--Project`.

**My opinion (and what I'm going to go ahead with for now, pending objections):**
No Team model, just have an M:N xref called "team".

**Notes on this reasoning:**
I think that the fundamental question here is whether or not the concept of "Team" as a database model is useful to us.

- The argument for a Team model is that there are some teams which stick together on a few projects and have a name (i.e. Sam, Robbie, and myself--Dream Team).
- The argument against that is that most people have different teams for each project, and often don't have a team "name" so the concept of a Team is kinda pointless.

I honestly think that the argument against is stronger. I don't know many named teams which have done more than one project. I also don't see a point in forcing people to make a Team when they were the only ones on the project.

Additionally converting the xref table to a Team model will be pretty trivial if we ever want to do so later.

**Comment by jackrosenthal** [comment]
> The argument for a Team model is that there are some teams which stick together on a few projects and have a name (i.e. Sam, Robbie, and myself--Dream Team).

ACM projects are open to anyone, not an exclusive team. Therefore, I don't think this model is what we want.
